export const ActionConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',

  PROFILE_REQUEST: 'PROFILE_REQUEST',
  PROFILE_ERROR: 'PROFILE_ERROR',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS',
  PROFILE_FLUSH: 'PROFILE_FLUSH',

  GENERATE_OTP_REQUEST: 'GENERATE_OTP_REQUEST',
  GENERATE_OTP_ERROR: 'GENERATE_OTP_ERROR',
  GENERATE_OTP_SUCCESS: 'GENERATE_OTP_SUCCESS',

  GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
  GET_ALL_PRODUCTS_ERROR: 'GET_ALL_PRODUCTS_ERROR',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',

  // Currency Details
  GET_CURRENCY_DETAILS_REQUEST: 'GET_CURRENCY_DETAILS_REQUEST',
  GET_CURRENCY_DETAILS_ERROR: 'GET_CURRENCY_DETAILS_ERROR',
  GET_CURRENCY_DETAILS_SUCCESS: 'GET_CURRENCY_DETAILS_SUCCESS',

  // Cart Details && Add to Cart

  CREATE_CART_REQUEST: 'CREATE_CART_REQUEST',
  CREATE_CART_ERROR: 'CREATE_CART_ERROR',
  CREATE_CART_SUCCESS: 'CREATE_CART_SUCCESS',

  GET_CART_DETAILS_REQUEST: 'GET_CART_DETAILS_REQUEST',
  GET_CART_DETAILS_ERROR: 'GET_CART_DETAILS_ERROR',
  GET_CART_DETAILS_SUCCESS: 'GET_CART_DETAILS_SUCCESS',

  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_ERROR: 'ADD_TO_CART_ERROR',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',

  UPDATE_CART_REQUEST: 'UPDATE_CART_REQUEST',
  UPDATE_CART_ERROR: 'UPDATE_CART_ERROR',
  UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',

  DELETE_ITEM_REQUEST: 'DELETE_ITEM_REQUEST',
  DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',
  DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
};
