export const ActionConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',

  GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
  GET_ALL_PRODUCTS_ERROR: 'GET_ALL_PRODUCTS_ERROR',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  // Currency Details
  GET_CURRENCY_DETAILS_REQUEST: 'GET_CURRENCY_DETAILS_REQUEST',
  GET_CURRENCY_DETAILS_ERROR: 'GET_CURRENCY_DETAILS_ERROR',
  GET_CURRENCY_DETAILS_SUCCESS: 'GET_CURRENCY_DETAILS_SUCCESS',
};
